version: "3"

services:
  jenkins:
    image: ${PROJECT_NAME}/jenkins
    container_name: ${PROJECT_NAME}-jenkins
    build:
      context: "./jenkins"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/jobs:/var/jenkins_home/jobs:rw
      - ./jenkins/secrets:/var/jenkins_home/secrets:rw
    environment:
      - JENKINS_JAVA_OPTIONS=-Xms1024m -Xmx2048m -Djava.awt.headless=true
    hostname: "jenkins"
    networks:
      app_net:
        ipv4_address: 172.30.0.11

  db:
    image: ${PROJECT_NAME}/mysql
    container_name: ${PROJECT_NAME}-mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    hostname: "db"
    networks:
      app_net:
        ipv4_address: 172.30.0.12

  web-app:
    image: ${PROJECT_NAME}/web
    container_name: ${PROJECT_NAME}-web
    build:
      context: "./amazonlinux"
      dockerfile: "Dockerfile"
    tty: true
    stdin_open: true
    privileged: true
    command: /sbin/init
    hostname: "web-app"
    networks:
      app_net:
        ipv4_address: 172.30.0.13

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
